version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      - truanayangi-network
    environment:
      - MONGO_DATA_DIR=/data/food-db
      - MONGO_LOG_DIR=/dev/null
    volumes:
        - data-orders-db:/data/orders-db
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  truanayangi-web:
    image: ${DOCKER_REGISTRY}orderweb
    networks:
      - truanayangi-network
    build:
      context: truanayangi-client
      dockerfile: Dockerfile

  food-api:
    image: ${DOCKER_REGISTRY}orderapi
    networks:
      - truanayangi-network
    build:
      context: food-service
      dockerfile: Dockerfile
   

networks:
  truanayangi-network:
  
volumes:
  data-db:
    
    
    

